#!/bin/sh -x

make mrproper

rm -rf ./toolchain
rm -f ./include/linux/ologk.h

cp -r ../../.clean/* ./

export ANDROID_MAJOR_VERSION=q

export ARCH=arm64

make exynos9611-xcoverproxx_defconfig

make -j8
